name = "avafe/template"
version = "0.1.0"
private = true

[target]
environment = "roblox"
lib = "src/init.luau"
build_files = ["src"]

[indices]
default = "https://github.com/pesde-pkg/index"
loneka = "https://github.com/loneka/registry"

[wally_indices]
default = "https://github.com/UpliftGames/wally-index"

[scripts]
roblox_sync_config_generator = ".pesde/scripts/roblox_sync_config_generator.luau"
sourcemap_generator = ".pesde/scripts/sourcemap_generator.luau"

[dev_dependencies]
scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
selene = { name = "pesde/selene", version = "^0.27.1", target = "lune" }
zap = { name = "pesde/zap", version = "^0.6.16", target = "lune" }

[dependencies]
t = { wally = "osyrisrblx/t", version = "^3.1.1" }
RateLimit = { wally = "red-blox/ratelimit", version = "^1.0.1" }
Future = { wally = "red-blox/future", version = "^1.0.1" }
Fetch = { wally = "red-blox/fetch", version = "^2.0.0" }
Signal = { wally = "sleitnick/signal", version = "^2.0.1" }
Loader = { wally = "sleitnick/loader", version = "^2.0.0" }
TableUtil = { wally = "sleitnick/table-util", version = "^1.2.1" }
EnumSerDes = { name = "avafe/enum_ser_des", version = "^0.1.0" }
ColorUtils = { wally = "csqrl/colour-utils", version = "^1.4.1" }

Wrapper = { name = "avafe/wrapper", version = "^0.1.0" }
Fusion = { wally = "elttob/fusion", version = "^0.3.0" }
Zone = { wally = "imavafe/zoneplus-reupload", version = "^3.2.0" }

OnyxUI = { wally = "imavafe/onyx-ui", version = "^0.5.3" }
NeoHotbar = { wally = "imavafe/neohotbar", version = "^1.1.1" }
TopbarPlus = { wally = "neura-studios/topbarplus", version = "^3.0.2" }
RagdollSystem = { wally = "leostormer/ragdoll-system", version = "^0.3.3" }

Universal = { name = "loneka/universal", version = "^0.1.1", index = "loneka" }
